name: LifeCalendar
options:
  bundleIdPrefix: com.sun
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 17.0
  configs:
    Debug: debug
    Release: release
  settings:
    base:
      DEVELOPMENT_TEAM: ""  # Add your Apple Developer Team ID here
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"

packages:
  LifeCalendarPackage:
    path: .
    productName: LifeCalendar

targets:
  iOSDemo:
    type: application
    platform: iOS
    sources:
      - path: iOSDemo
        excludes:
          - "*.xcodeproj"
    settings:
      base:
        INFOPLIST_FILE: iOSDemo/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sun.LifeCalendarDemo
    dependencies:
      - package: LifeCalendarPackage
        product: LifeCalendar

schemes:
  iOSDemo:
    build:
      targets:
        iOSDemo: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
